### ISSUE TITLE
Status of project? No commits in almost an year.

### ISSUE THREAD

**Issue by madskaddie** [fizzed/stork#28]
Due to having an issue with the maven plugin with a java 11 target app I realized that there are no commits in master over the last year. Is the project still maintained?

Do you need help with anything?

**Comment by jjlauer** [comment]
Hey @madskaddie project is definitely still maintained.  We just haven't hit any bugs w/ it, thus no commits.  We have made its sister project, Blaze, Java 11 compat recently since that's the primary way we fire up Stork deploys.  Would be great if you were interested in PR'ing features such as any Java 11 changes required and/or rsync-like deploys where only files that have changed are pushed out.   I'm still keen on not relying on rsync for a 100% Java ssh experience.

**Comment by jjlauer** [comment]
New PR just submitted by community a few days ago :-) and new release pushed out.

**Comment by madskaddie** [comment]
Thanks :)

Regarding:
> rsync-like deploys where only files that have changed are pushed out

What do you have in mind? I can imagine something like:
- Make a manifest based on the target's _current_ directory. MD5 per file should be enough?
- Transfer the manifest back to the controlling host
- Making an archive with the diff files + "TODO script" (if we simply copy the current and override, we will include deleted files, so we need to know which files we copy from current and files from the uploaded archive)
- Send the archive to the target's temp dir
- Rollout the version by following the "TODO script"

Does stork-deploy accounts for concurrency at filesystem level?
